### ISSUE TITLE
dúvida sobre o resultado da batalha

### ISSUE THREAD

**Issue by 1995william** [IterisConsultoria/desafioSomoSback#2]
Gostaria de saber sobre o retorno do resultado da batalha. Posso retornar o valor da carta vencedora com os campo referente os atributos dela.  ex: "name": "Bulbasaur"
        "attributes": {
            "hp": 45,
            "attack": 49,
            "defense": 49,
            "special-attack": 65,
            "special-defense": 65,
            "speed": 45
        }
    }
ao invés do exemplo do requisito número 4 do README?

**Comment by cesarimnida** [comment]
Oi William.
Infelizmente esse requisito precisa ser feito por completo, dizendo qual carta foi vencedora, qual carta acabou perdendo e qual carta ganhou em cada categoria.
Lembrando que você ainda precisa fazer a tratativa do empate e também contabilizar as vitórias de cada jogador. 😄

**Comment by 1995william** [comment]
certo. Obrigado!
