### ISSUE TITLE
Tema do desafio Back-end

### ISSUE THREAD

**Issue by han19githtbr** [IterisConsultoria/desafioSomoSback#3]
Olá, boa noite, tenho uma dúvida a respeito do desafio. O tema tem que ser obrigatoriamente de Pokemons, ou posso escolher outro tema? Por exemplo cartas comparando meios de transporte? 

Já agradeço

**Comment by douglasfernandesjr** [comment]
OIá, Handy!

É um jogo de comparação de cartas, usamos como exemplo um jogo de cartas de Pokémon, mas isso acaba sendo somente um rótulo.

Desde que cumpra os objetivos descritos, você pode usar outra temática e usar outros 6 atributos de comparação.

**Comment by han19githtbr** [comment]
Olá, @douglasfernandesjr . Obrigado pela informação. Tenho outra dúvida: para fazer as operações como cadastrar uma carta, a entrada obrigatoriamente tem que ser no formato "json", ou posso usar como entrada uma tabela no MySQL por exemplo?  Já agradeço

**Comment by douglasfernandesjr** [comment]
@han19githtbr, você precisa tomar esta decisão baseado no que está sendo pedido no desafio. 

O proposito é desenvolver uma API REST que atenda aos requisitos propostos.
